### ISSUE TITLE
Delegate template parameter incorrectly treated as compile-time

### ISSUE THREAD

**Issue by PostSharpBot** [postsharp/Caravela#647]
This code:

```c#
using Metalama.Framework.Aspects;
using Metalama.Framework.Code;

class MyAspect : TypeAspect
{
    public override void BuildAspect(IAspectBuilder<INamedType> builder)
    {
        builder.Advice.IntroduceMethod(builder.Target, nameof(Template));
    }

    [Template]
    void Template(Func<object> f)
    {
        f();
    }
}

[MyAspect]
class Target
{
}
```

fails when building the compile-time compilation with:

> error CS0149: Method name expected

A variation that uses `Action` instead fails with:

> error LAMA0200: A compile-time value of type 'void' was used in a context where a run-time value was expected.

**Comment by PostSharpBot** [comment]
The ticket was imported from [TP-35001](https://postsharp.tpondemand.com/entity/35001).
Original creator: p***o [at] postsharp.net
Original creation time: 2024-05-27T12:27:27Z
Original severity: Annoying
Original business value: Average
Original source: Internal

**Comment by PostSharpAgent** [comment]
## Phase 1: Understanding the Issue

**Issue:** When a template method has a parameter of a delegate type (`Func<T>`, `Action`, etc.), Metalama incorrectly classifies the parameter as compile-time instead of run-time.

**Expected behavior:** Delegate-type parameters in templates (without `[CompileTime]` annotation) should be treated as run-time parameters. They should:
- Remain in the generated method signature
- Be callable at run-time

**Actual behavior:** The delegate parameters are treated as compile-time, causing:
1. `Func<object> f` case: `error CS0149: Method name expected` — the delegate parameter is removed from compile-time code, making `f()` invalid
2. `Action` variation: `error LAMA0200` — the delegate invocation is wrongly treated as a compile-time expression returning `void`

**Root cause hypothesis:** The compile-time/run-time scope classification logic incorrectly identifies delegate types as compile-time-only, possibly because the classification doesn't properly handle delegate types that wrap run-time-or-compile-time generic arguments.

Moving to Phase 2: reproducing the bug with a regression test.

— Claude for @gfraiteur

**Comment by PostSharpAgent** [comment]
## Phase 2: Bug Reproduced

The bug has been reproduced with a regression test in PR #1395.

**Test:** `IntroduceMethod_DelegateParameter` in `Metalama.Framework.Tests.AspectTests/Tests/Aspects/TemplateParameters/`

The test confirms that when a template method has delegate-type parameters (`Func<object>`, `Action`), the compile-time compilation fails with:
- `error CS0149: Method name expected` for `f()`
- `error CS0149: Method name expected` for `a()`

This confirms the delegate parameters are incorrectly removed from the compile-time code (treated as compile-time parameters instead of run-time parameters).

Moving to Phase 3: implementing the fix.

— Claude for @gfraiteur

**Comment by PostSharpAgent** [comment]
## Phase 3: Fix Implemented

**Root cause:** In `TemplateAnnotator.VisitInvocationExpression`, when a run-time template parameter of delegate type (e.g., `Func<object> f`) is invoked (`f()`), the invocation expression was annotated with `RunTimeTemplateParameter` scope (inherited from the expression scope). The `MustBeTransformed()` method in `TemplatingScopeExtensions` explicitly excludes `RunTimeTemplateParameter` from being transformed, so the invocation was kept as literal code in the compile-time compilation. Since the template parameter was rewritten to type `ExpressionSyntax` in the compile-time code, calling `f()` on an `ExpressionSyntax` caused `CS0149: Method name expected`.

**Fix:** In `TemplateAnnotator.VisitInvocationExpression`, when annotating the invocation with scope and the expression scope is `RunTimeTemplateParameter`, use `RunTimeOnly` instead. The invocation of a delegate template parameter produces a run-time value, not another template parameter reference, so it should be transformed into syntax factory code.

**Test results:** All 2054 aspect tests pass on net8.0 with zero regressions. Moving to Phase 4: consolidated build and test.

— Claude for @gfraiteur

**Comment by PostSharpAgent** [comment]
**Progress update (Phase 4 — Build & Test):**

- `Build.ps1 build` completed successfully with zero warnings.
- `Build.ps1 test` is currently running. Main solution tests (aspect tests, template tests, linker tests, unit tests, workspace tests) all passed. Standalone tests are still executing.
- Will check for zero warnings after test completion, then finalize.

— Claude for @PostSharpAgent

**Comment by PostSharpAgent** [comment]
**Summary: Issue #647 fixed and verified.**

**Root cause:** In `TemplateAnnotator.VisitInvocationExpression`, when a run-time template parameter (e.g., `Action a` or `Func<object> f`) was invoked, the invocation expression inherited the `RunTimeTemplateParameter` scope from the parameter reference. However, `MustBeTransformed()` explicitly excludes `RunTimeTemplateParameter` scope, causing the invocation to not be transformed into syntax factory code. The parameter itself was correctly rewritten to `ExpressionSyntax` type in compile-time code, but the `f()` / `a()` invocation was left as-is — resulting in `CS0149: Method name expected` because you can't invoke an `ExpressionSyntax` directly.

**Fix:** In `TemplateAnnotator.VisitInvocationExpression`, when the expression scope is `RunTimeTemplateParameter`, the invocation scope is now set to `RunTimeOnly` (instead of inheriting `RunTimeTemplateParameter`). This ensures the invocation gets properly transformed to syntax factory code while the parameter reference itself retains its `RunTimeTemplateParameter` scope.

**Regression test:** Added `IntroduceMethod_DelegateParameter` aspect test covering both `Action` and `Func<object>` delegate parameters in introduced methods.

**Verification:**
- `Build.ps1 build`: Passed with zero warnings
- `Build.ps1 test`: All tests passed (including new regression test)

**PR:** https://github.com/metalama/Metalama/pull/1395

— Claude for @PostSharpAgent

**Comment by PostSharpAgent** [comment]
**Note:** Attempted to trigger a TeamCity DebugBuild for branch `topic/2026.1/647-delegate-runtime-template-parameter` but the CI token doesn't have 'Run build' permission for this project. A manual TeamCity build trigger or the automatic PR build will verify the fix in CI.

— Claude for @PostSharpAgent

**Comment by gfraiteur** [comment]
Released in [Metalama 2026.1.4-preview](https://github.com/metalama/Metalama/releases/tag/release/2026.1.4-preview).
