### ISSUE TITLE
Tuple deconstruction in compile-time foreach causes compilation errors

### ISSUE THREAD

**Issue by PostSharpBot** [postsharp/Caravela#643]
```
[Template]
public void RestoreState( [CompileTime] IReadOnlyList<(IField MementoField, IProperty Property)> pairs )
{
    foreach ( var (MementoField, Property) in pairs )
    {
        Property.Value = MementoField.Value;
    }
}

```

**Comment by PostSharpBot** [comment]
The ticket was imported from [TP-35075](https://postsharp.tpondemand.com/entity/35075).
Original creator: d***l [at] postsharp.net
Original creation time: 2024-06-11T18:23:51Z
Original severity: Annoying
Original business value: Average
Original source: Internal

**Comment by PostSharpAgent** [comment]
## Phase 1: Understanding

This bug is about tuple deconstruction in a **compile-time `foreach`** loop within a T# template. The template code:

```csharp
[Template]
public void RestoreState( [CompileTime] IReadOnlyList<(IField MementoField, IProperty Property)> pairs )
{
    foreach ( var (MementoField, Property) in pairs )
    {
        Property.Value = MementoField.Value;
    }
}
```

Since `pairs` is marked `[CompileTime]`, the `foreach` should be a compile-time loop. The tuple deconstruction `var (MementoField, Property)` uses the `ParenthesizedVariableDesignation` syntax and should create compile-time local variables for each tuple element.

**Expected behavior:** The loop should be unrolled at compile time, with `MementoField` and `Property` resolved as compile-time variables holding the `IField` and `IProperty` values from each tuple.

**Actual behavior:** Compilation errors occur, indicating the template engine doesn't properly handle `ParenthesizedVariableDesignation` in the foreach variable declaration context.

This is distinct from the fixed issue #1277 (which addressed `(var x, var y) = expr` assignment syntax). This issue is specifically about `var (x, y)` in the `foreach` iteration variable pattern.

Proceeding to Phase 2: reproduce the issue with a regression test.

— Claude for @gfraiteur

**Comment by PostSharpAgent** [comment]
## Phase 2: Bug Reproduced

The bug is confirmed. Two regression tests added in PR #1392:

1. **ForEachTupleDeconstruction** — basic tuple deconstruction (`var (name, value)`) in a compile-time foreach over `List<(string, int)>`
2. **ForEachTupleDeconstructionCodeModel** — tuple deconstruction with code model data (parameter names and types)

Both tests fail with:
```
AssertionFailedException: The node '[DeclarationExpression] var (<SingleVariableDesignation>, <SingleVariableDesignation>) ' must be annotated.
```

**Root cause**: The `DeclarationExpression` node inside a `ForEachVariableStatement` (used for `var (x, y)` syntax) is not being annotated with compile-time scope information by the template annotation pass. When `TemplateCompilerRewriter.IsCompileTimeCode` encounters this unannotated node, it throws an assertion failure.

The stack trace shows the issue originates in:
- `TemplateCompilerRewriter.IsCompileTimeCode()` → `GetFromParent()` at line 258
- Called from `MetaSyntaxRewriter.TransformForEachVariableStatement()`

Proceeding to Phase 3: implement the fix.

— Claude for @gfraiteur

**Comment by PostSharpAgent** [comment]
## Phase 4: Build and Test Progress

**Fix implemented and committed.** The fix adds:

1. `VisitForEachVariableStatement` to `TemplateAnnotator.cs` — annotates the `DeclarationExpression` and its child `SingleVariableDesignation` nodes with compile-time scope when the foreach expression is compile-time.
2. `VisitForEachVariableStatement` override in `TemplateCompilerRewriter.cs` — handles the compile-time case by emitting a `ForEachVariableStatement` that executes at compile time.

**Test results so far:**
- 2 new regression tests pass (ForEachTupleDeconstruction, ForEachTupleDeconstructionCodeModel)
- All 19 ForEach-related tests pass
- All 10 TupleDeconstruction tests pass
- All 315 template tests pass
- `Build.ps1 build` succeeds with zero warnings

Currently running `Build.ps1 test`. Will finalize after tests complete.

— Claude for @gfraiteur

**Comment by PostSharpAgent** [comment]
## Fix completed

PR: #1392 — ready for review.

### Root cause

`TemplateAnnotator.cs` had `VisitForEachStatement` (for `foreach (var x in expr)`) but was missing `VisitForEachVariableStatement` (for `foreach (var (x, y) in expr)` — the tuple deconstruction variant). This meant the `DeclarationExpression` inside a `ForEachVariableStatement` was never annotated with compile-time scope, causing an `AssertionFailedException` in `TemplateCompilerRewriter`.

Similarly, `TemplateCompilerRewriter.cs` lacked a `VisitForEachVariableStatement` override, so compile-time loop unrolling could not handle the deconstruction syntax.

### Fix

Added `VisitForEachVariableStatement` to both `TemplateAnnotator.cs` and `TemplateCompilerRewriter.cs`, modeled after the existing `VisitForEachStatement` handlers but adapted for the `ForEachVariableStatement` syntax structure.

### Test results

- Two new regression tests: `ForEachTupleDeconstruction` (basic) and `ForEachTupleDeconstructionCodeModel` (code model)
- `Build.ps1 build`: passed with zero warnings
- `Build.ps1 test`: all test suites passed with zero failures

— Claude for @gfraiteur

**Comment by gfraiteur** [comment]
Released in [Metalama 2026.1.4-preview](https://github.com/metalama/Metalama/releases/tag/release/2026.1.4-preview).
