### ISSUE TITLE
Invoking IMethod with array of arguments causes confusing error

### ISSUE THREAD

**Issue by PostSharpBot** [postsharp/Caravela#784]
Test this code:

method.Invoke( new object[] { 1 } )

**Comment by PostSharpBot** [comment]
The ticket was imported from [TP-33499](https://postsharp.tpondemand.com/entity/33499).
Original creator: g***l [at] postsharp.net
Original creation time: 2023-07-12T09:25:18Z
Original severity: Annoying
Original business value: Low
Original source: Internal

**Comment by PostSharpAgent** [comment]
## Investigation Summary

**Understanding**: The `IMethodInvoker.Invoke` method has the signature `Invoke(params dynamic?[] args)`. When a user writes `method.Invoke(new object[] { 1 })`, they likely intend to pass the array elements as individual arguments. However, because of `params`, C# treats the `object[]` as a single argument rather than unpacking it. This results in confusing generated code that tries to pass an `object[]` as the first argument to the target method.

The fix should detect when an `object[]` (or similar array) is passed as a single argument and either automatically unpack it or provide a clear diagnostic message.

Starting Phase 2: reproducing the issue with a regression test.

— Claude for @gfraiteur

**Comment by PostSharpAgent** [comment]
## Phase 2 Complete: Bug Reproduced

The bug is confirmed. When `method.Invoke(new object[] { 1 })` is called in a template, the generated code is:

```csharp
this.Method((global::System.Int32)new object[] { 1 });
```

This produces `CS0030: Cannot convert type 'object[]' to 'int'` — a confusing error for the user.

The `Invoke(params dynamic?[] args)` signature means C# `params` semantics should unpack the array, but in the T# template context, the array expression is being treated as a single argument.

Draft PR: https://github.com/metalama/Metalama/pull/1446

Moving to Phase 3 to implement the fix.

— Claude for @gfraiteur

**Comment by PostSharpAgent** [comment]
## Phase 3 Complete: Fix Implemented

Added diagnostic **LAMA0014** that detects when an array expression is passed as a single argument to `IMethodInvoker.Invoke` but the target method's parameter is not an array type.

**Before** (confusing):
```
error CS0030: Cannot convert type 'object[]' to 'int'
```

**After** (clear):
```
error LAMA0014: An array of type 'object[]' was passed as a single argument to 'TargetClass.Method(int)', 
but the parameter 'x' expects type 'int'. The IMethodInvoker.Invoke method uses 'params', so each argument 
should be passed individually (e.g., method.Invoke(arg1, arg2)), or use method.Invoke(IEnumerable<IExpression>) 
to pass a dynamic collection of arguments.
```

**Changes:**
- `GeneralDiagnosticDescriptors.cs`: Added `LAMA0014` diagnostic definition
- `MethodInvoker.cs`: Added array-type mismatch detection in `InvokeCore`
- Two test files: error case and valid-array-param case

Full build passed. Running test suite now.

— Claude for @gfraiteur

**Comment by PostSharpAgent** [comment]
## Phase 5 Complete: PR Ready for Review

PR https://github.com/metalama/Metalama/pull/1446 is ready for review.

**Summary of fix:**
- Added diagnostic LAMA0014 that detects when an array expression is passed as a single argument to `IMethodInvoker.Invoke` but the target method's parameter is not an array type.
- The error message clearly explains the `params` semantics and suggests passing arguments individually or using `Invoke(IEnumerable<IExpression>)`.
- Full build passes with zero warnings, all tests pass.

— Claude for @gfraiteur

**Comment by PostSharpAgent** [comment]
## Session 2: PR Finalized

Verified the fix from the previous session:
- `Build.ps1 build` passes with zero warnings
- Both tests (`InvokeWithArrayArgument` and `InvokeWithArrayArgument_ValidArrayParam`) pass on both net8.0 and net48

PR https://github.com/metalama/Metalama/pull/1446 is now marked as ready for review. Review requested from @gfraiteur.

— Claude for @gfraiteur

**Comment by PostSharpAgent** [comment]
## Session 3: Addressing Review Feedback

Implementing the changes requested by @gfraiteur on PR #1446:
1. Removing LAMA0014 diagnostic — using `ArgumentOutOfRangeException` for invalid cases instead
2. Unpacking `object[]` arrays into individual arguments instead of reporting errors

Starting implementation now.

— Claude for @gfraiteur

**Comment by PostSharpAgent** [comment]
## Session 3 Complete: Review Feedback Addressed

All review feedback from @gfraiteur has been implemented:

1. **Removed LAMA0014 diagnostic** — no longer needed since we now unpack the array instead of reporting an error.
2. **Array unpacking implemented** — when `method.Invoke(new object[] { 1 })` is called and the target method doesn't expect an array parameter, the array elements are unpacked into individual `array[i]` expressions.
3. **Added multi-parameter test** — verifies unpacking works for `Method(int x, string y)` with `Invoke(new object[] { 1, "hello" })`.

**Build**: zero warnings. **Tests**: all pass (`Build.ps1 test`).

PR: https://github.com/metalama/Metalama/pull/1446

— Claude for @gfraiteur

**Comment by PostSharpAgent** [comment]
## Session 4: Implementing TemplateAnnotator Fix

Addressing @gfraiteur's review feedback to fix the root cause in `TemplateAnnotator` rather than `MethodInvoker`:

1. When a scope-neutral `object[]` is passed to a `dynamic[]` parameter, prefer compile-time scope so the array is evaluated at compile time
2. Revert the `MethodInvoker` unpacking logic (no longer needed)
3. Update test expected outputs

Starting implementation now.

— Claude for @gfraiteur

**Comment by PostSharpAgent** [comment]
**Progress update (Phase 3→4)**

The fix has been moved from `MethodInvoker` to `TemplateAnnotator` as requested. The approach:

- In `TemplateAnnotator.VisitInvocationExpression`, detect when an `object[]` array creation expression is passed to a `dynamic[]` parameter
- Visit the expression with `CompileTimeOnly` scope context instead of `RunTimePreferred`, so the array elements stay compile-time and are unpacked as individual arguments by the Invoke method
- Only `object[]` arrays are treated this way — typed arrays like `int[]` are left as actual argument values

All 2099 aspect tests pass (30 skipped), including all 142 invoker tests and the ValidArrayParam edge case. Running `Build.ps1 build` next to verify zero warnings.

— Claude for @gfraiteur

**Comment by PostSharpAgent** [comment]
**Fix complete**

The fix is implemented in PR #1446, now in TemplateAnnotator as requested.

**Approach:** When an `object[]` array creation expression is passed to a `dynamic[]` parameter (e.g., `method.Invoke(new object[] { 1 })`), the TemplateAnnotator detects this before visiting the expression and visits it with a `CompileTimeOnly` scope context instead of `RunTimePreferred`. This way, the array elements stay as compile-time values and are properly unpacked as individual arguments by the Invoke method at compile time.

**Key design decisions:**
- Only `object[]` arrays match (checked via `SpecialType.System_Object`). Typed arrays like `int[]`, `string[]`, etc. are left unchanged as actual argument values.
- Only explicit array creation expressions (`ArrayCreationExpressionSyntax` / `ImplicitArrayCreationExpressionSyntax`) match. Method calls returning arrays (like in CacheAttribute) are unaffected.
- The argument scope is set to `CompileTimeOnly` and the UserExpression annotation is skipped for these arrays.

**Test results:** All tests pass — `Build.ps1 build` (zero warnings) and `Build.ps1 test` (all frameworks, zero failures).

— Claude for @gfraiteur

**Comment by gfraiteur** [comment]
The behavior is too hacky. Better to keep the existing, simpler rules.
